plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation("org.apache.logging.log4j:log4j-core:2.23.1")
    implementation("org.apache.logging.log4j:log4j-api:2.23.1")
    implementation("com.lmax:disruptor:4.0.0")

    compileOnly("org.projectlombok:lombok:1.18.48")
    annotationProcessor("org.projectlombok:lombok:1.18.48")

    // Permite analizar el peso en MB de las clases con calculo desglosado
    implementation("org.openjdk.jol:jol-core:0.17")

    // OSHI permite medir la memoria fisica del servidor
    implementation("com.github.oshi:oshi-core:6.8.3")

}

test {
    useJUnitPlatform()
}
